#import "DollarDefaultGestures.h"
#import "DollarPointCloud.h"
#import "DollarPoint.h"

DollarPointCloud * MakePointCloud(NSString *name, NSArray *points) {
    return [[DollarPointCloud alloc] initWithName:name points:points];
}

DollarPoint * MakePoint(float x, float y, int id) {
    return [[DollarPoint alloc] initWithId:@(id) x:x y:y];
}

@implementation DollarDefaultGestures

+ (id)defaultPointClouds {
    static NSArray *defaultPointClouds = nil;
    if (!defaultPointClouds) {
        defaultPointClouds = [self pointClouds];
    }
    return defaultPointClouds;
}

+ (NSMutableArray *)pointClouds {
    NSMutableArray *pointClouds = [NSMutableArray array];
    
	pointClouds[0] = MakePointCloud(@"T", @[
                                    MakePoint(30,7,1),
                                    MakePoint(103,7,1),
                                    
                                    MakePoint(66,7,2),
                                    MakePoint(66,87,2)
                                    ]);
    
	pointClouds[1] = MakePointCloud(@"N", @[
                                    MakePoint(177,92,1),
                                    MakePoint(177,2,1),
                                    
                                    MakePoint(182,1,2),
                                    MakePoint(246,95,2),
                                    
                                    MakePoint(247,87,3),
                                    MakePoint(247,1,3)
                                    ]);
    
	pointClouds[2] = MakePointCloud(@"D", @[
                                    MakePoint(345,9,1),
                                    MakePoint(345,87,1),
                                    
                                    MakePoint(351,8,2),
                                    MakePoint(363,8,2),
                                    MakePoint(372,9,2),
                                    MakePoint(380,11,2),
                                    MakePoint(386,14,2),
                                    MakePoint(391,17,2),
                                    MakePoint(394,22,2),
                                    MakePoint(397,28,2),
                                    MakePoint(399,34,2),
                                    MakePoint(400,42,2),
                                    MakePoint(400,50,2),
                                    MakePoint(400,56,2),
                                    MakePoint(399,61,2),
                                    MakePoint(397,66,2),
                                    MakePoint(394,70,2),
                                    MakePoint(391,74,2),
                                    MakePoint(386,78,2),
                                    MakePoint(382,81,2),
                                    MakePoint(377,83,2),
                                    MakePoint(372,85,2),
                                    MakePoint(367,87,2),
                                    MakePoint(360,87,2),
                                    MakePoint(355,88,2),
                                    MakePoint(349,87,2)
                                    ]);
    
	pointClouds[3] = MakePointCloud(@"P", @[
                                    MakePoint(507,8,1),
                                    MakePoint(507,87,1),
                                    
                                    MakePoint(513,7,2),
                                    MakePoint(528,7,2),
                                    MakePoint(537,8,2),
                                    MakePoint(544,10,2),
                                    MakePoint(550,12,2),
                                    MakePoint(555,15,2),
                                    MakePoint(558,18,2),
                                    MakePoint(560,22,2),
                                    MakePoint(561,27,2),
                                    MakePoint(562,33,2),
                                    MakePoint(561,37,2),
                                    MakePoint(559,42,2),
                                    MakePoint(556,45,2),
                                    MakePoint(550,48,2),
                                    MakePoint(544,51,2),
                                    MakePoint(538,53,2),
                                    MakePoint(532,54,2),
                                    MakePoint(525,55,2),
                                    MakePoint(519,55,2),
                                    MakePoint(513,55,2),
                                    MakePoint(510,55,2)
                                    ]);
    
	pointClouds[4] = MakePointCloud(@"X", @[
                                    MakePoint(30,146,1),
                                    MakePoint(106,222,1),
                                    
                                    MakePoint(30,225,2),
                                    MakePoint(106,146,2)
                                    ]);
    
	pointClouds[5] = MakePointCloud(@"H", @[
                                    MakePoint(188,137,1),
                                    MakePoint(188,225,1),
                                    
                                    MakePoint(188,180,2),
                                    MakePoint(241,180,2),
                                    
                                    MakePoint(241,137,3),
                                    MakePoint(241,225,3)
                                    ]);
    
	pointClouds[6] = MakePointCloud(@"I", @[
                                    MakePoint(371,149,1),
                                    MakePoint(371,221,1),
                                    
                                    MakePoint(341,149,2),
                                    MakePoint(401,149,2),
                                    
                                    MakePoint(341,221,3),
                                    MakePoint(401,221,3)
                                    ]);
    
    pointClouds[7] = MakePointCloud(@"M", @[
                                    MakePoint(33, 277, 1),
                                    MakePoint(33, 276, 1),
                                    MakePoint(32, 274, 1),
                                    MakePoint(31, 271, 1),
                                    MakePoint(31, 267, 1),
                                    MakePoint(30, 262, 1),
                                    MakePoint(30, 253, 1),
                                    MakePoint(30, 236, 1),
                                    MakePoint(30, 217, 1),
                                    MakePoint(30, 192, 1),
                                    MakePoint(35, 163, 1),
                                    MakePoint(43, 138, 1),
                                    MakePoint(53, 116, 1),
                                    MakePoint(63, 98, 1),
                                    MakePoint(73, 88, 1),
                                    MakePoint(84, 79, 1),
                                    MakePoint(98, 75, 1),
                                    MakePoint(116, 73, 1),
                                    MakePoint(129, 75, 1),
                                    MakePoint(141, 86, 1),
                                    MakePoint(149, 102, 1),
                                    MakePoint(153, 133, 1),
                                    MakePoint(153, 188, 1),
                                    MakePoint(153, 226, 1),
                                    MakePoint(153, 269, 1),
                                    MakePoint(153, 304, 1),
                                    MakePoint(154, 321, 1),
                                    MakePoint(155, 331, 1),
                                    MakePoint(156, 337, 1),
                                    MakePoint(157, 339, 1),
                                    MakePoint(158, 333, 1),
                                    MakePoint(158, 315, 1),
                                    MakePoint(160, 289, 1),
                                    MakePoint(165, 226, 1),
                                    MakePoint(178, 165, 1),
                                    MakePoint(193, 125, 1),
                                    MakePoint(202, 115, 1),
                                    MakePoint(210, 106, 1),
                                    MakePoint(218, 101, 1),
                                    MakePoint(226, 99, 1),
                                    MakePoint(245, 100, 1),
                                    MakePoint(263, 125, 1),
                                    MakePoint(273, 153, 1),
                                    MakePoint(276, 179, 1),
                                    MakePoint(279, 246, 1),
                                    MakePoint(279, 285, 1),
                                    ]);
    
    pointClouds[7] = MakePointCloud(@"M", @[
                                    MakePoint(20, 254, 1),
                                    MakePoint(20, 253, 1),
                                    MakePoint(20, 252, 1),
                                    MakePoint(20, 251, 1),
                                    MakePoint(20, 249, 1),
                                    MakePoint(20, 246, 1),
                                    MakePoint(20, 241, 1),
                                    MakePoint(20, 229, 1),
                                    MakePoint(20, 212, 1),
                                    MakePoint(20, 197, 1),
                                    MakePoint(24, 181, 1),
                                    MakePoint(28, 163, 1),
                                    MakePoint(31, 153, 1),
                                    MakePoint(37, 138, 1),
                                    MakePoint(42, 129, 1),
                                    MakePoint(46, 124, 1),
                                    MakePoint(51, 119, 1),
                                    MakePoint(53, 118, 1),
                                    MakePoint(56, 118, 1),
                                    MakePoint(62, 118, 1),
                                    MakePoint(66, 120, 1),
                                    MakePoint(69, 125, 1),
                                    MakePoint(73, 129, 1),
                                    MakePoint(75, 134, 1),
                                    MakePoint(77, 142, 1),
                                    MakePoint(79, 152, 1),
                                    MakePoint(81, 168, 1),
                                    MakePoint(83, 187, 1),
                                    MakePoint(85, 206, 1),
                                    MakePoint(89, 239, 1),
                                    MakePoint(90, 249, 1),
                                    MakePoint(91, 257, 1),
                                    MakePoint(91, 261, 1),
                                    MakePoint(91, 263, 1),
                                    MakePoint(91, 262, 1),
                                    MakePoint(91, 258, 1),
                                    MakePoint(91, 247, 1),
                                    MakePoint(91, 235, 1),
                                    MakePoint(92, 216, 1),
                                    MakePoint(94, 196, 1),
                                    MakePoint(99, 171, 1),
                                    MakePoint(104, 141, 1),
                                    MakePoint(111, 110, 1),
                                    MakePoint(117, 92, 1),
                                    MakePoint(122, 78, 1),
                                    MakePoint(126, 71, 1),
                                    MakePoint(131, 67, 1),
                                    MakePoint(135, 66, 1),
                                    MakePoint(138, 66, 1),
                                    MakePoint(142, 67, 1),
                                    MakePoint(146, 74, 1),
                                    MakePoint(151, 83, 1),
                                    MakePoint(155, 96, 1),
                                    MakePoint(160, 107, 1),
                                    MakePoint(164, 128, 1),
                                    MakePoint(167, 147, 1),
                                    MakePoint(171, 186, 1),
                                    MakePoint(172, 209, 1),
                                    MakePoint(174, 242, 1),
                                    MakePoint(174, 255, 1),
                                    MakePoint(174, 264, 1),
                                    MakePoint(174, 267, 1),
                                    MakePoint(173, 266, 1),
                                    MakePoint(173, 264, 1),
                                    ]);
    
    pointClouds[8] = MakePointCloud(@"L", @[
                                    MakePoint(75, 84, 1),
                                    MakePoint(75, 88, 1),
                                    MakePoint(75, 121, 1),
                                    MakePoint(75, 157, 1),
                                    MakePoint(75, 186, 1),
                                    MakePoint(71, 245, 1),
                                    MakePoint(67, 279, 1),
                                    MakePoint(65, 305, 1),
                                    MakePoint(63, 327, 1),
                                    MakePoint(63, 337, 1),
                                    MakePoint(63, 345, 1),
                                    MakePoint(63, 352, 1),
                                    MakePoint(63, 354, 1),
                                    MakePoint(63, 355, 1),
                                    MakePoint(64, 355, 1),
                                    MakePoint(68, 355, 1),
                                    MakePoint(80, 355, 1),
                                    MakePoint(96, 355, 1),
                                    MakePoint(119, 354, 1),
                                    MakePoint(145, 352, 1),
                                    MakePoint(165, 350, 1),
                                    MakePoint(187, 349, 1),
                                    MakePoint(196, 348, 1),
                                    MakePoint(205, 347, 1),
                                    MakePoint(209, 347, 1),
                                    MakePoint(211, 347, 1),
                                    ]);
    
    pointClouds[9] = MakePointCloud(@"L", @[
                                    MakePoint(102, 76, 1),
                                    MakePoint(102, 100, 1),
                                    MakePoint(102, 136, 1),
                                    MakePoint(102, 170, 1),
                                    MakePoint(102, 243, 1),
                                    MakePoint(102, 279, 1),
                                    MakePoint(102, 318, 1),
                                    MakePoint(102, 337, 1),
                                    MakePoint(102, 351, 1),
                                    MakePoint(97, 317, 2),
                                    MakePoint(102, 317, 2),
                                    MakePoint(132, 317, 2),
                                    MakePoint(180, 317, 2),
                                    MakePoint(244, 317, 2),
                                    MakePoint(310, 314, 2),
                                    ]);
    
    
    pointClouds[10] = MakePointCloud(@"E", @[
                                     
                                     MakePoint(187, 72, 1),
                                     MakePoint(178, 72, 1),
                                     MakePoint(173, 72, 1),
                                     MakePoint(161, 72, 1),
                                     MakePoint(156, 72, 1),
                                     MakePoint(145, 75, 1),
                                     MakePoint(132, 90, 1),
                                     MakePoint(123, 102, 1),
                                     MakePoint(116, 118, 1),
                                     MakePoint(109, 137, 1),
                                     MakePoint(106, 153, 1),
                                     MakePoint(105, 176, 1),
                                     MakePoint(105, 192, 1),
                                     MakePoint(110, 206, 1),
                                     MakePoint(119, 214, 1),
                                     MakePoint(132, 223, 1),
                                     MakePoint(150, 228, 1),
                                     MakePoint(165, 230, 1),
                                     MakePoint(180, 231, 1),
                                     MakePoint(188, 232, 1),
                                     MakePoint(198, 232, 1),
                                     MakePoint(195, 231, 1),
                                     MakePoint(180, 227, 1),
                                     MakePoint(161, 227, 1),
                                     MakePoint(143, 231, 1),
                                     MakePoint(128, 243, 1),
                                     MakePoint(118, 266, 1),
                                     MakePoint(115, 340, 1),
                                     MakePoint(120, 364, 1),
                                     MakePoint(133, 388, 1),
                                     MakePoint(144, 398, 1),
                                     MakePoint(169, 410, 1),
                                     MakePoint(191, 407, 1),
                                     MakePoint(224, 383, 1),
                                     ]);
    
    pointClouds[11] = MakePointCloud(@"E", @[
                                     
                                     MakePoint(182, 59, 1),
                                     MakePoint(180, 59, 1),
                                     MakePoint(177, 59, 1),
                                     MakePoint(173, 59, 1),
                                     MakePoint(165, 59, 1),
                                     MakePoint(159, 59, 1),
                                     MakePoint(141, 65, 1),
                                     MakePoint(126, 82, 1),
                                     MakePoint(120, 91, 1),
                                     MakePoint(115, 100, 1),
                                     MakePoint(111, 111, 1),
                                     MakePoint(110, 120, 1),
                                     MakePoint(110, 130, 1),
                                     MakePoint(110, 137, 1),
                                     MakePoint(111, 144, 1),
                                     MakePoint(116, 149, 1),
                                     MakePoint(121, 155, 1),
                                     MakePoint(127, 159, 1),
                                     MakePoint(131, 162, 1),
                                     MakePoint(134, 164, 1),
                                     MakePoint(138, 166, 1),
                                     MakePoint(140, 167, 1),
                                     MakePoint(140, 168, 1),
                                     MakePoint(139, 168, 1),
                                     MakePoint(137, 168, 1),
                                     MakePoint(132, 169, 1),
                                     MakePoint(123, 178, 1),
                                     MakePoint(118, 187, 1),
                                     MakePoint(112, 223, 1),
                                     MakePoint(112, 245, 1),
                                     MakePoint(112, 269, 1),
                                     MakePoint(119, 293, 1),
                                     MakePoint(129, 313, 1),
                                     MakePoint(144, 332, 1),
                                     MakePoint(150, 335, 1),
                                     MakePoint(156, 336, 1),
                                     ]);
    
    pointClouds[12] = MakePointCloud(@"E", @[
                                     
                                     MakePoint(208, 64, 1),
                                     MakePoint(202, 64, 1),
                                     MakePoint(192, 64, 1),
                                     MakePoint(181, 64, 1),
                                     MakePoint(176, 65, 1),
                                     MakePoint(169, 67, 1),
                                     MakePoint(163, 71, 1),
                                     MakePoint(159, 74, 1),
                                     MakePoint(154, 76, 1),
                                     MakePoint(150, 79, 1),
                                     MakePoint(147, 81, 1),
                                     MakePoint(139, 87, 1),
                                     MakePoint(136, 89, 1),
                                     MakePoint(132, 91, 1),
                                     MakePoint(128, 93, 1),
                                     MakePoint(123, 95, 1),
                                     MakePoint(118, 99, 1),
                                     MakePoint(112, 103, 1),
                                     MakePoint(107, 108, 1),
                                     MakePoint(101, 114, 1),
                                     MakePoint(97, 118, 1),
                                     MakePoint(92, 123, 1),
                                     MakePoint(87, 126, 1),
                                     MakePoint(84, 129, 1),
                                     MakePoint(81, 133, 1),
                                     MakePoint(78, 137, 1),
                                     MakePoint(76, 139, 1),
                                     MakePoint(75, 142, 1),
                                     MakePoint(73, 146, 1),
                                     MakePoint(72, 151, 1),
                                     MakePoint(72, 156, 1),
                                     MakePoint(72, 161, 1),
                                     MakePoint(72, 167, 1),
                                     MakePoint(72, 171, 1),
                                     MakePoint(72, 176, 1),
                                     MakePoint(72, 181, 1),
                                     MakePoint(72, 185, 1),
                                     MakePoint(72, 191, 1),
                                     MakePoint(73, 196, 1),
                                     MakePoint(75, 201, 1),
                                     MakePoint(82, 211, 1),
                                     MakePoint(87, 216, 1),
                                     MakePoint(94, 220, 1),
                                     MakePoint(101, 224, 1),
                                     MakePoint(110, 228, 1),
                                     MakePoint(126, 234, 1),
                                     MakePoint(133, 235, 1),
                                     MakePoint(140, 236, 1),
                                     MakePoint(145, 237, 1),
                                     MakePoint(151, 237, 1),
                                     MakePoint(162, 237, 1),
                                     MakePoint(165, 237, 1),
                                     MakePoint(170, 237, 1),
                                     MakePoint(171, 238, 1),
                                     MakePoint(170, 238, 1),
                                     MakePoint(159, 238, 1),
                                     MakePoint(149, 238, 1),
                                     MakePoint(138, 238, 1),
                                     MakePoint(127, 239, 1),
                                     MakePoint(118, 241, 1),
                                     MakePoint(106, 246, 1),
                                     MakePoint(102, 249, 1),
                                     MakePoint(98, 253, 1),
                                     MakePoint(96, 257, 1),
                                     MakePoint(92, 262, 1),
                                     MakePoint(91, 266, 1),
                                     MakePoint(85, 277, 1),
                                     MakePoint(83, 281, 1),
                                     MakePoint(81, 284, 1),
                                     MakePoint(81, 286, 1),
                                     MakePoint(81, 288, 1),
                                     MakePoint(81, 289, 1),
                                     MakePoint(81, 291, 1),
                                     MakePoint(82, 292, 1),
                                     MakePoint(85, 295, 1),
                                     MakePoint(88, 298, 1),
                                     MakePoint(91, 302, 1),
                                     MakePoint(96, 305, 1),
                                     MakePoint(101, 309, 1),
                                     MakePoint(107, 313, 1),
                                     MakePoint(113, 319, 1),
                                     MakePoint(125, 333, 1),
                                     MakePoint(131, 340, 1),
                                     MakePoint(142, 345, 1),
                                     MakePoint(149, 351, 1),
                                     MakePoint(156, 355, 1),
                                     MakePoint(160, 358, 1),
                                     MakePoint(165, 360, 1),
                                     MakePoint(170, 363, 1),
                                     MakePoint(172, 364, 1),
                                     MakePoint(175, 366, 1),
                                     MakePoint(178, 368, 1),
                                     MakePoint(181, 370, 1),
                                     MakePoint(183, 372, 1),
                                     MakePoint(185, 374, 1),
                                     MakePoint(187, 376, 1),
                                     MakePoint(191, 377, 1),
                                     MakePoint(193, 377, 1),
                                     MakePoint(196, 377, 1),
                                     ]);
    
    pointClouds[13] = MakePointCloud(@"S", @[
                                     
                                     MakePoint(221, 75, 1),
                                     MakePoint(221, 74, 1),
                                     MakePoint(220, 72, 1),
                                     MakePoint(217, 70, 1),
                                     MakePoint(213, 67, 1),
                                     MakePoint(206, 64, 1),
                                     MakePoint(196, 60, 1),
                                     MakePoint(184, 59, 1),
                                     MakePoint(163, 58, 1),
                                     MakePoint(150, 58, 1),
                                     MakePoint(134, 58, 1),
                                     MakePoint(122, 58, 1),
                                     MakePoint(112, 58, 1),
                                     MakePoint(95, 63, 1),
                                     MakePoint(88, 66, 1),
                                     MakePoint(81, 71, 1),
                                     MakePoint(74, 76, 1),
                                     MakePoint(68, 82, 1),
                                     MakePoint(59, 97, 1),
                                     MakePoint(54, 112, 1),
                                     MakePoint(53, 121, 1),
                                     MakePoint(53, 131, 1),
                                     MakePoint(53, 142, 1),
                                     MakePoint(54, 154, 1),
                                     MakePoint(58, 164, 1),
                                     MakePoint(65, 177, 1),
                                     MakePoint(81, 191, 1),
                                     MakePoint(110, 205, 1),
                                     MakePoint(128, 210, 1),
                                     MakePoint(145, 212, 1),
                                     MakePoint(167, 217, 1),
                                     MakePoint(181, 221, 1),
                                     MakePoint(195, 227, 1),
                                     MakePoint(207, 235, 1),
                                     MakePoint(219, 246, 1),
                                     MakePoint(233, 268, 1),
                                     MakePoint(239, 279, 1),
                                     MakePoint(242, 290, 1),
                                     MakePoint(245, 305, 1),
                                     MakePoint(240, 318, 1),
                                     MakePoint(227, 321, 1),
                                     MakePoint(209, 324, 1),
                                     MakePoint(183, 328, 1),
                                     MakePoint(167, 329, 1),
                                     MakePoint(137, 330, 1),
                                     MakePoint(127, 329, 1),
                                     MakePoint(119, 325, 1),
                                     MakePoint(112, 319, 1),
                                     MakePoint(106, 313, 1),
                                     ]);
    
    pointClouds[14] = MakePointCloud(@"S", @[
                                     
                                     MakePoint(219, 106, 1),
                                     MakePoint(217, 103, 1),
                                     MakePoint(213, 95, 1),
                                     MakePoint(206, 89, 1),
                                     MakePoint(198, 83, 1),
                                     MakePoint(185, 79, 1),
                                     MakePoint(168, 79, 1),
                                     MakePoint(150, 79, 1),
                                     MakePoint(132, 81, 1),
                                     MakePoint(114, 88, 1),
                                     MakePoint(102, 94, 1),
                                     MakePoint(92, 105, 1),
                                     MakePoint(87, 114, 1),
                                     MakePoint(83, 128, 1),
                                     MakePoint(81, 148, 1),
                                     MakePoint(87, 193, 1),
                                     MakePoint(100, 212, 1),
                                     MakePoint(121, 231, 1),
                                     MakePoint(167, 257, 1),
                                     MakePoint(186, 268, 1),
                                     MakePoint(196, 275, 1),
                                     MakePoint(207, 286, 1),
                                     MakePoint(214, 301, 1),
                                     MakePoint(215, 321, 1),
                                     MakePoint(215, 339, 1),
                                     MakePoint(208, 355, 1),
                                     MakePoint(191, 367, 1),
                                     MakePoint(117, 378, 1),
                                     MakePoint(78, 371, 1),
                                     MakePoint(62, 365, 1),
                                     ]);
    
    pointClouds[15] = MakePointCloud(@"S", @[
                                     
                                     MakePoint(208, 67, 1),
                                     MakePoint(202, 65, 1),
                                     MakePoint(188, 64, 1),
                                     MakePoint(173, 64, 1),
                                     MakePoint(153, 64, 1),
                                     MakePoint(133, 68, 1),
                                     MakePoint(115, 75, 1),
                                     MakePoint(106, 80, 1),
                                     MakePoint(97, 86, 1),
                                     MakePoint(92, 93, 1),
                                     MakePoint(91, 100, 1),
                                     MakePoint(91, 106, 1),
                                     MakePoint(91, 119, 1),
                                     MakePoint(94, 133, 1),
                                     MakePoint(102, 151, 1),
                                     MakePoint(111, 166, 1),
                                     MakePoint(135, 191, 1),
                                     MakePoint(157, 212, 1),
                                     MakePoint(170, 228, 1),
                                     MakePoint(182, 240, 1),
                                     MakePoint(192, 256, 1),
                                     MakePoint(196, 266, 1),
                                     MakePoint(196, 281, 1),
                                     MakePoint(196, 290, 1),
                                     MakePoint(187, 301, 1),
                                     MakePoint(177, 308, 1),
                                     MakePoint(165, 315, 1),
                                     MakePoint(154, 320, 1),
                                     MakePoint(148, 323, 1),
                                     MakePoint(142, 323, 1),
                                     ]);
    
    pointClouds[16] = MakePointCloud(@"M", @[
                                     
                                     MakePoint(70, 111, 1),
                                     MakePoint(70, 133, 1),
                                     MakePoint(70, 164, 1),
                                     MakePoint(71, 205, 1),
                                     MakePoint(74, 238, 1),
                                     MakePoint(77, 262, 1),
                                     MakePoint(82, 277, 1),
                                     MakePoint(85, 282, 1),
                                     MakePoint(87, 279, 1),
                                     MakePoint(90, 253, 1),
                                     MakePoint(92, 219, 1),
                                     MakePoint(94, 192, 1),
                                     MakePoint(96, 163, 1),
                                     MakePoint(98, 138, 1),
                                     MakePoint(100, 122, 1),
                                     MakePoint(102, 115, 1),
                                     MakePoint(104, 113, 1),
                                     MakePoint(105, 112, 1),
                                     MakePoint(107, 113, 1),
                                     MakePoint(109, 125, 1),
                                     MakePoint(111, 140, 1),
                                     MakePoint(114, 150, 1),
                                     MakePoint(116, 158, 1),
                                     MakePoint(119, 162, 1),
                                     MakePoint(124, 162, 1),
                                     MakePoint(131, 144, 1),
                                     MakePoint(140, 115, 1),
                                     MakePoint(147, 92, 1),
                                     MakePoint(154, 71, 1),
                                     MakePoint(159, 58, 1),
                                     MakePoint(162, 54, 1),
                                     MakePoint(166, 54, 1),
                                     MakePoint(168, 68, 1),
                                     MakePoint(170, 96, 1),
                                     MakePoint(173, 134, 1),
                                     MakePoint(178, 169, 1),
                                     MakePoint(185, 208, 1),
                                     MakePoint(191, 244, 1),
                                     MakePoint(196, 278, 1),
                                     MakePoint(201, 295, 1),
                                     ]);
    
    
    pointClouds[17] = MakePointCloud(@"f", @[
                                     
                                     MakePoint(242, 102, 1),
                                     MakePoint(240, 99, 1),
                                     MakePoint(236, 95, 1),
                                     MakePoint(232, 90, 1),
                                     MakePoint(224, 81, 1),
                                     MakePoint(211, 72, 1),
                                     MakePoint(196, 63, 1),
                                     MakePoint(180, 59, 1),
                                     MakePoint(162, 59, 1),
                                     MakePoint(142, 68, 1),
                                     MakePoint(129, 82, 1),
                                     MakePoint(122, 102, 1),
                                     MakePoint(120, 126, 1),
                                     MakePoint(120, 161, 1),
                                     MakePoint(124, 198, 1),
                                     MakePoint(134, 238, 1),
                                     MakePoint(147, 273, 1),
                                     MakePoint(92, 173, 2),
                                     MakePoint(115, 173, 2),
                                     MakePoint(144, 174, 2),
                                     MakePoint(171, 178, 2),
                                     ]);
    
    pointClouds[18] = MakePointCloud(@"f", @[
                                     
                                     MakePoint(226, 79, 1),
                                     MakePoint(211, 77, 1),
                                     MakePoint(196, 74, 1),
                                     MakePoint(174, 72, 1),
                                     MakePoint(154, 72, 1),
                                     MakePoint(130, 72, 1),
                                     MakePoint(114, 72, 1),
                                     MakePoint(101, 74, 1),
                                     MakePoint(93, 76, 1),
                                     MakePoint(89, 78, 1),
                                     MakePoint(87, 82, 1),
                                     MakePoint(87, 87, 1),
                                     MakePoint(89, 96, 1),
                                     MakePoint(94, 111, 1),
                                     MakePoint(98, 132, 1),
                                     MakePoint(101, 155, 1),
                                     MakePoint(102, 184, 1),
                                     MakePoint(104, 214, 1),
                                     MakePoint(105, 242, 1),
                                     MakePoint(106, 260, 1),
                                     MakePoint(108, 269, 1),
                                     MakePoint(109, 273, 1),
                                     MakePoint(110, 273, 1),
                                     MakePoint(111, 261, 1),
                                     MakePoint(92, 190, 2),
                                     MakePoint(108, 190, 2),
                                     MakePoint(132, 190, 2),
                                     MakePoint(159, 190, 2),
                                     MakePoint(183, 190, 2),
                                     ]);
    
    pointClouds[19] = MakePointCloud(@"f", @[
                                     
                                     MakePoint(225, 130, 1),
                                     MakePoint(223, 120, 1),
                                     MakePoint(217, 109, 1),
                                     MakePoint(210, 97, 1),
                                     MakePoint(202, 86, 1),
                                     MakePoint(194, 76, 1),
                                     MakePoint(185, 70, 1),
                                     MakePoint(175, 68, 1),
                                     MakePoint(165, 68, 1),
                                     MakePoint(154, 71, 1),
                                     MakePoint(145, 79, 1),
                                     MakePoint(137, 92, 1),
                                     MakePoint(132, 111, 1),
                                     MakePoint(129, 133, 1),
                                     MakePoint(129, 158, 1),
                                     MakePoint(129, 186, 1),
                                     MakePoint(132, 218, 1),
                                     MakePoint(138, 246, 1),
                                     MakePoint(144, 267, 1),
                                     MakePoint(147, 282, 1),
                                     MakePoint(147, 290, 1),
                                     MakePoint(118, 212, 2),
                                     MakePoint(138, 210, 2),
                                     MakePoint(164, 204, 2),
                                     MakePoint(194, 195, 2),
                                     ]);
    
    pointClouds[20] = MakePointCloud(@"f", @[
                                     
                                     MakePoint(167, 88, 1),
                                     MakePoint(166, 84, 1),
                                     MakePoint(162, 79, 1),
                                     MakePoint(157, 74, 1),
                                     MakePoint(151, 71, 1),
                                     MakePoint(144, 71, 1),
                                     MakePoint(135, 74, 1),
                                     MakePoint(130, 88, 1),
                                     MakePoint(126, 112, 1),
                                     MakePoint(125, 137, 1),
                                     MakePoint(125, 167, 1),
                                     MakePoint(125, 205, 1),
                                     MakePoint(125, 240, 1),
                                     MakePoint(128, 272, 1),
                                     MakePoint(130, 298, 1),
                                     MakePoint(131, 318, 1),
                                     MakePoint(132, 330, 1),
                                     MakePoint(137, 225, 2),
                                     MakePoint(159, 219, 2),
                                     ]);
    
    
    return pointClouds;
}

@end